apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  generation: 1
  labels:
    app: kube-prometheus-stack
    heritage: Helm
    release: prometheus
  name: {{ .Values.name }}
spec:
  groups:
    - name: {{ .Release.Namespace }}.{{ .Values.name }}.rules
      rules:
        # Alert if the cron job failed.
        - alert: {{ snakecase .Values.name }}_cron_job_failed
          annotations:
            description: "{{ .Values.name }} cron_job_failed."
          expr: kube_job_status_failed{namespace="{{ .Release.Namespace }}",job_name=~"{{ .Values.name }}-.*"} > {{.Values.alerts.standard.infra.cronjob_failed_threshold}}
          labels:
            severity: critical
            servicealert: "true"
            service: {{ .Values.name }}
            namespace: {{ .Release.Namespace }}