apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: {{ .Values.httpPort}}
    - name: metrics-port
      port: 2121
      targetPort: {{ .Values.metricsPort}}
  selector:
    app: {{ .Values.name }}
  type: NodePort
---