apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.name}}
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
  endpoints:
    {{- if and .Values.metricsScrapeInterval (ne .Values.metricsScrapeInterval 0) }}
    - port: metrics-port
      interval: {{ .Values.metricsScrapeInterval }}
      path: /metrics
    {{- end }}
---