{{- if not .Values.schedule -}}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  generation: 1
  labels:
    app: kube-prometheus-stack
    heritage: Helm
    release: prometheus
  name: {{ .Values.name }}
spec:
  groups:
    - name: {{ .Values.name }}.rules
      rules:
        # Alert if the number of pods goes down minimum over a period of time.
        - alert: {{ snakecase .Values.name }}_pod_below_minimum_replicas
          annotations:
            description: "{{ .Values.name }} pods below minimum number of replicas."
          expr: sum(kube_deployment_status_replicas_available{namespace="{{ .Release.Namespace }}", deployment="{{ .Values.name }}"}) - sum(kube_horizontalpodautoscaler_spec_min_replicas{namespace="{{ .Release.Namespace }}", horizontalpodautoscaler="{{ .Values.name }}"}) < 0
          for: 3m
          labels:
            severity: critical
            servicealert: "true"
            service: {{ .Values.name }}
            namespace: {{ .Release.Namespace }}
        # Alert if the pod restarts.
        {{- if ne .Values.alerts.standard.infra.pod_restart_threshold -1.0 }}
        - alert: {{ snakecase .Values.name }}_pod_restarts
          annotations:
            description: "{{ .Values.name }} pods restarts"
          expr: sum(increase(kube_pod_container_status_restarts_total{namespace="{{ .Release.Namespace }}",pod=~"{{ .Values.name }}-.*" }[{{ .Values.alerts.standard.infra.pod_restart_time_window }}])) > {{ .Values.alerts.standard.infra.pod_restart_threshold }}
          labels:
            severity: critical
            servicealert: "true"
            service: {{ .Values.name }}
            namespace: {{ .Release.Namespace }}
        {{- end}}
        # Alert if replicas of service are in unavailable state.
        {{- if ne .Values.alerts.standard.infra.unavailable_replicas_threshold -1.0 }}
        - alert: {{ snakecase .Values.name }}_unavailable_replicas
          annotations:
            description: "{{ .Values.name }} required number of replicas are unavailable"
          expr: sum(kube_deployment_status_replicas_unavailable{deployment="{{ .Values.name }}",namespace="{{ .Release.Namespace }}"}) > {{ .Values.alerts.standard.infra.unavailable_replicas_threshold }}
          labels:
            severity: critical
            servicealert: "true"
            service: {{ .Values.name }}
            namespace: {{ .Release.Namespace }}
        {{- end}}
        # Alert if the deployment has zero replicas.
        - alert: {{ snakecase .Values.name }}_deployment_has_zero_replicas
          annotations:
            description: "{{ .Values.name }} deployment has zero replicas."
          expr: sum(kube_deployment_status_replicas{namespace="{{ .Release.Namespace }}",  deployment="{{ .Values.name }}"}) == 0
          labels:
            severity: critical
            servicealert: "true"
            service: {{ .Values.name }}
            namespace: {{ .Release.Namespace }}
        #  Alert if replica count crosses the threshold percentage of max pod count.
        {{- if ne .Values.alerts.standard.infra.hpa_nearing_max_pod_threshold -1.0 }}
        - alert: {{ snakecase .Values.name }}_hpa_nearing_max_pod_count
          annotations:
            description: "{{ .Values.name }} nearing HPA max pod count threshold."
          expr: (sum(kube_horizontalpodautoscaler_status_current_replicas{namespace="{{ .Release.Namespace }}", horizontalpodautoscaler="{{ .Values.name }}"}) / sum(kube_horizontalpodautoscaler_spec_max_replicas{namespace="{{ .Release.Namespace }}", horizontalpodautoscaler="{{ .Values.name }}"})) * 100 >= {{ .Values.alerts.standard.infra.hpa_nearing_max_pod_threshold }}
          labels:
            severity: critical
            servicealert: "true"
            service: {{ .Values.name }}
            namespace: {{ .Release.Namespace }}
        {{- end}}
        # Alert if memory utilization is beyond threshold for service in any pod
        {{- if ne .Values.alerts.standard.infra.service_memory_utilization_threshold -1.0 }}
        - alert: {{ snakecase .Values.name }}_service_memory_utilization_above_{{ .Values.alerts.standard.infra.service_memory_utilization_threshold}}
          annotations:
            description: "{{ .Values.name }}  service memory utilization above {{ .Values.alerts.standard.infra.service_memory_utilization_threshold}} percentage"
          expr: sum(container_memory_working_set_bytes{pod=~"{{ .Values.name }}-.*", container="{{ .Values.name }}", namespace="{{ .Release.Namespace }}"}) / sum(container_spec_memory_limit_bytes{pod=~"{{ .Values.name }}-.*",container="{{ .Values.name }}",namespace="{{ .Release.Namespace }}"}) *100 > {{ .Values.alerts.standard.infra.service_memory_utilization_threshold }}
          labels:
            severity: critical
            servicealert: "true"
            service: {{ .Values.name }}
            namespace: {{ .Release.Namespace }}
        {{- end}}
        # Alert if CPU utilization is beyond threshold for service in any pod
        {{- if ne .Values.alerts.standard.infra.service_cpu_utilization_threshold -1.0 }}
        - alert: {{ snakecase .Values.name }}_service_cpu_utilization_above_{{ .Values.alerts.standard.infra.service_cpu_utilization_threshold}}
          annotations:
            description: "{{ .Values.name }} service cpu utilization above {{ .Values.alerts.standard.infra.service_cpu_utilization_threshold}} percentage"
          expr: ((sum(irate(container_cpu_usage_seconds_total{container="{{ .Values.name }}", namespace="{{ .Release.Namespace }}"}[{{ .Values.alerts.standard.infra.service_cpu_utilization_time_window }}]))  / sum(container_spec_cpu_quota{container="{{ .Values.name }}", namespace="{{ .Release.Namespace }}"} / container_spec_cpu_period{container="{{ .Values.name }}", namespace="{{ .Release.Namespace }}"})  ) * 100)  > {{ .Values.alerts.standard.infra.service_cpu_utilization_threshold }} 
          labels:
            severity: critical
            servicealert: "true"
            service: {{ .Values.name }}
            namespace: {{ .Release.Namespace }}
        {{- end}}
        # Alert if  application health-check failure increased
        {{- if ne .Values.alerts.standard.infra.health_check_failure_threshold -1.0 }}
        - alert: {{ snakecase .Values.name }}_healthcheck_failure_increased
          annotations:
            description: "{{ .Values.name }} apps health-check failure beyond threshold."
          expr: sum(increase(zs_http_response_count{namespace="{{ .Release.Namespace }}",path="/.well-known/health-check",status!="200",service="{{ .Values.name }}"}[{{ .Values.alerts.standard.infra.health_check_failure_time_window }}]))> {{ .Values.alerts.standard.infra.health_check_failure_threshold }}
          labels:
            severity: critical
            servicealert: "true"
            service: {{ .Values.name }}
            namespace: {{ .Release.Namespace }}
         {{- end }}

        # Custom Alerts dependent on services
        {{- range $v := .Values.alerts.custom }}
        - alert: {{ snakecase $v.name }}
          annotations:
            description: {{ $v.description | quote }}
          {{- if ne (default 0.0 $v.percentile) 0.0 }}
          expr: (histogram_quantile({{ $v.percentile }}, sum(rate({{ $v.alert_rule }}{service="{{ $.Values.name }}"}[{{ $v.time_window }}])) by ({{ $v.sum_by_label }}))){{ $v.query_operator | default (printf ">") }} {{ $v.threshold }}
          {{- else }}
            {{- if  ne $v.sum_by_label ""  }}
               {{- if  ne $v.label_value ""  }}
          expr: sum by ({{ $v.sum_by_label }}) (increase({{ $v.alert_rule }}{service="{{ $.Values.name }}", namespace="{{ $.Release.Namespace }}"{{printf ", %s=\"%s\"" $v.sum_by_label $v.label_value }}{{ printf "}["}}{{ printf $v.time_window}}{{ printf "]))"}}{{ $v.query_operator | default (printf " > ") }}{{ $v.threshold}}
               {{- else}}
          expr: sum by ({{ $v.sum_by_label }}) (increase({{ $v.alert_rule }}{service="{{ $.Values.name }}", namespace="{{ $.Release.Namespace }}"{{ printf "}["}}{{ printf $v.time_window}}{{ printf "]))"}}{{  $v.query_operator | default (printf ">") }}{{ $v.threshold}}
               {{- end }}
            {{- end }}
            {{- if  eq $v.sum_by_label ""  }}
          expr: sum(increase({{ $v.alert_rule }}{service="{{ $.Values.name }}", namespace="{{ $.Release.Namespace }}"{{ printf "}["}}{{ printf $v.time_window}}{{ printf "]))"}}{{ $v.query_operator | default (printf ">") }}{{ $v.threshold}}
            {{- end }}
          {{- end }}
          labels:
            servicealert: "true"
            namespace: {{ $.Release.Namespace }}
            service: {{ $.Values.name }}
            {{- range $key,$value := $v.labels }}
            {{ $key }}: {{ $value }}
            {{- end }}
        {{- end }}
---
{{- end -}}