apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-ui
#  name: hm-ui
data:
#  environment.js: |
#    if (typeof window !== 'undefined')
#    window.env = {
#      REACT_APP_BASE_URL: "https://api-stage.hiringmotion.com",
#      REACT_APP_CLIENT_ID: "1004747005329-p5t06i14ja167lh3v6mo8gl0t4jdqsv3.apps.googleusercontent.com",
#      REACT_APP_FARO_APP_NAME: "hm-ui-ui-local",
#      REACT_APP_FARO_URL: "https://grafana-agent.observability-prod.gcp.zopsmart.com/collect",
#    }


  environment.js: |
    if (typeof window !== 'undefined')
    window.env = {
      BASE_URL: "https://api.stage.kops.dev",
      GOOGLE_LOGIN_CLIENT_ID: "1004747005329-p5t06i14ja167lh3v6mo8gl0t4jdqsv3.apps.googleusercontent.com",
      FARO_APP_NAME: "zs-cloud-ui-stage",
      FARO_APP_URL: "https://grafana-agent.observability-prod.gcp.zopsmart.com/collect",
    }