{{- if  .Values.schedule -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.name}}
  labels:
    app: {{ .Values.name }}
  annotations:
    configmap.reloader.stakater.com/reload: "{{ .Values.name }}"
spec:
  schedule: {{ .Values.schedule | quote }}
  suspend: {{ .Values.suspend }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          name: {{ .Values.name}}
          labels:
            app: {{ .Values.name }}
        spec:
          {{- if ne .Values.secret_key_reference "" }}
          serviceAccountName: secrets-account
          volumes:
            - name: app-secrets
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: "{{ .Values.name }}-secrets-application"
          {{- end }}
          containers:
            - name: {{ .Values.name }}
              image: {{ .Values.image }}
              imagePullPolicy: IfNotPresent
              ports:
                - name: metrics-port
                  containerPort: {{ .Values.metricsPort }}
              envFrom:
                {{- range $i, $name := .Values.envFrom.configmaps }}
                - configMapRef:
                    name: {{ $name }}
                {{- end }}
                {{- range $i, $name := .Values.envFrom.secrets }}
                - secretRef:
                    name: {{ $name }}
                 {{- end }}
              env:
                {{- range $k,$v := .Values.env }}
                  {{- if ne (toString $v) ""}}
                - name: {{ $k | quote }}
                  value: {{ $v | quote }}
                  {{- end }}
                {{- end }}
                  # Volume mount is required for the secret to sync with kubernetes secret
              volumeMounts:
              {{- if .Values.volumeMounts }}
              {{- range $k,$v := .Values.volumeMounts.configmaps }}
                - name: {{ $v.name }}
                  mountPath: {{ $v.mountPath }}
                {{- if ne $v.subPath "" }}
                  subPath: {{ $v.subPath }}
                {{- end }}
              {{- end }}
              {{- end }}
              {{- if ne .Values.secret_key_reference "" }}
                - name: app-secrets
                  mountPath: "/mnt/secrets-store"
                  readOnly: true
              {{- if .Values.env.DB_ENABLE_SSL }}
                - name: ssl-secrets
                  mountPath: /etc/ssl
              {{- end }}
              {{- end }}
              resources:
                requests:
                  memory: {{.Values.minMemory | quote }}
                  cpu: {{.Values.minCPU | quote }}
                limits:
                {{ if ne .Values.maxMemory "" }}
                  memory: {{.Values.maxMemory| quote }}
                {{ end }}
                {{ if ne .Values.maxCPU "" }}
                  cpu: {{.Values.maxCPU | quote }}
                {{ end }}
          restartPolicy: Never

  {{- end -}}