{{- if  .Values.schedule -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.name}}
  labels:
    app: {{ .Values.name }}
spec:
  schedule: {{ .Values.schedule | quote }}
  suspend: {{ .Values.suspend | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          name: {{ .Values.name}}
          labels:
            app: {{ .Values.name }}
        spec:
          {{- if ne .Values.secret_key_reference "" }}
          serviceAccountName: secrets-account
          volumes:
            - name: app-secrets
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: "{{ .Values.name }}-secrets-application"
          {{- end }}
          containers:
            - name: {{ .Values.name }}
              image: {{ .Values.image }}
              imagePullPolicy: IfNotPresent
              ports:
                - name: metrics-port
                  containerPort: {{ .Values.metricsPort }}
              envFrom:
                {{- if ne .Values.secret_key_reference "" }}
                - secretRef:
                    name: {{ tpl $.Values.secret_key_reference $}}
                {{- end }}
                - configMapRef:
                    name: {{ tpl $.Values.config_map_reference $}}
              env:
                {{- range $k,$v := .Values.env }}
                - name: {{ $k | quote }}
                  value: {{ $v | quote }}
                {{- end }}
              {{- if ne .Values.secret_key_reference "" }}
              volumeMounts:
                - name: app-secrets
                  mountPath: "/mnt/secrets-store"
                  readOnly: true
              {{- end }}
              resources:
                requests:
                  memory: {{.Values.minMemory | quote }}
                  cpu: {{.Values.minCPU | quote }}
                limits:
                  memory: {{.Values.maxMemory| quote }}
                  cpu: {{.Values.maxCPU | quote }}
          restartPolicy: Never

  {{- end -}}