{{- if not .Values.schedule -}}
---
{{- if (lt (float64 .Values.kubernetes_version) 1.23)}}
apiVersion: autoscaling/v2beta2
  {{else}}
apiVersion: autoscaling/v2
  {{- end}}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.name }}
spec:
  maxReplicas: {{ .Values.maxReplicas | default 4}}
  minReplicas: {{ .Values.minReplicas | default 2}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.name }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa_cpu_limit  }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa_memory_limit  }}
---
  {{- end -}}