apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.name}}
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
  endpoints:
    - port: metrics-port
      interval: {{.Values.metricsScrapeInterval }}
      path: /metrics
---