name: Push Helm Repo to GAR

on:
  push:
    branches:
      - main

jobs:
  push_to_gar:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v')}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.5.0' # You can specify the version you want to use

      - name: Package Helm Chart
        run: |
          mkdir charts
          helm package service --version ${GITHUB_REF#refs/*/} -d ./charts1   
          helm repo index ./charts1

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.DEPLOYMENT_KEY }}

      - name: Authenticate with Docker configuration using access token
        run: |
          gcloud auth print-access-token | helm registry login -u oauth2accesstoken \
          --password-stdin https://us-central1-docker.pkg.dev

      - name: Push Helm Chart to GAR
        run: |
          helm push ./charts1/service-${GITHUB_REF#refs/*/}.tgz oci://us-central1-docker.pkg.dev/zs-devops/zs-helm
